name: Ürünleri Güncelle

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Kodu al
      uses: actions/checkout@v3

    - name: Python kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Gereksinimleri kur
      run: pip install requests

    - name: Ürün verisini çek
      run: python scripts/urun_tarayici.py

    - name: Değişiklikleri kaydet ve push et
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add public/urunler.json
        git commit -m "🔁 JSON güncellendi" || echo "No changes to commit"
        git push
