name: Ürünleri Güncelle

on:
  schedule:
    - cron: "0 3 * * *"   # Her gün 06:00 (TRT, UTC+3) == 03:00 UTC
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

env:
  TRENDYOL_API_KEY: ${{ secrets.TRENDYOL_API_KEY }}
  TRENDYOL_API_SECRET: ${{ secrets.TRENDYOL_API_SECRET }}
  TRENDYOL_SUPPLIER_ID: ${{ secrets.TRENDYOL_SUPPLIER_ID }}

jobs:
  sync:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests

      # ✅ PING: Postman'da çalışanla aynı endpoint (integration/product/sellers)
      - name: Trendyol ping (integration endpoint)
        run: |
          python - <<'PY'
          import os, base64, requests
          key=os.getenv("TRENDYOL_API_KEY")
          sec=os.getenv("TRENDYOL_API_SECRET")
          sid=os.getenv("TRENDYOL_SUPPLIER_ID")
          tok = base64.b64encode(f"{key}:{sec}".encode()).decode()
          headers = {
            "Authorization": f"Basic {tok}",
            "Accept": "application/json",
            "Content-Type": "application/json",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36"
          }
          url = f"https://apigw.trendyol.com/integration/product/sellers/{sid}/products?approved=true&page=0&size=1"
          r = requests.get(url, headers=headers, timeout=30)
          print("PING status:", r.status_code)
          # Log güvenliği için body'yi yazmıyoruz; headerları göstermek yeterli
          print("Resp headers:", dict(r.headers))
          if r.status_code != 200:
              raise SystemExit("❌ Ping başarısız! (integration endpoint) - key/secret/sellerId/yetkiyi kontrol et.")
          PY

      - name: Fetch products from Trendyol
        run: python scripts/urun_tarayici.py

      - name: Detect changes
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git add -N public/urunler.json
          if git diff --quiet -- public/urunler.json; then
            echo "NO_CHANGES=1" >> $GITHUB_ENV
          else
            echo "NO_CHANGES=0" >> $GITHUB_ENV
          fi

      - name: Commit & push
        if: env.NO_CHANGES == '0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .
          git commit -m "chore: Trendyol ürünleri güncellendi ($(date -u +'%Y-%m-%dT%H:%M:%SZ'))"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{_
